<a href="https://colab.research.google.com/github/AleRR94/analisis-smartmenu/blob/main/notas/web_scraping_menu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

print("Librerías listas")

Librerías listas

In [10]:
# Simulación de código oculto (HTML) que Python descargará de la web de delivery
# Ejemplo de 5 postres reales de la competencia con sus precios y calificaciones
codigo_html_web = """
<div class="platillo-card">
    <span class="producto-nombre">Pastel de Tres Leches Individual</span>
    <span class="producto-precio">$85.00</span>
    <span class="producto-rating">4.8 estrellas</span>
</div>
<div class="platillo-card">
    <span class="producto-nombre">Cheesecake de Frutos Rojos</span>
    <span class="producto-precio">$95.00</span>
    <span class="producto-rating">4.6 estrellas</span>
</div>
<div class="platillo-card">
    <span class="producto-nombre">Muffin de Chocolate</span>
    <span class="producto-precio">$45.00</span>
    <span class="producto-rating">4.2 estrellas</span>
</div>
<div class="platillo-card">
    <span class="producto-nombre">Tartaleta de Mango de la Casa</span>
    <span class="producto-precio">$75.00</span>
    <span class="producto-rating">4.9 estrellas</span>
</div>
<div class="platillo-card">
    <span class="producto-nombre">Pastel Imposible (Chocoflan)</span>
    <span class="producto-precio">$65.00</span>
    <span class="producto-rating">4.5 estrellas</span>
</div>
"""

# Pasar el código al "rastrillo" BeautifulSoup para que lo ordene
soup = BeautifulSoup(codigo_html_web, 'html.parser')

# Crear listas vacías para ir guardando los datos limpios
nombres_postres = []
precios_postres = []

# Python que buscará las etiquetas específicas de internet
for tarjeta in soup.find_all('div', class_='platillo-card'):
    nombre = tarjeta.find('span', class_='producto-nombre').text
    precio = tarjeta.find('span', class_='producto-precio').text

    # Guardar el resultado de las listas
    nombres_postres.append(nombre)
    precios_postres.append(precio)

# Convertir los datos raspados en una tabla de Pandas (DataFrame)
df_competencia = pd.DataFrame({
    'Postre_Competidor': nombres_postres,
    'Precio_Venta': precios_postres
})

# Mostrar el resultado en pantalla
df_competencia

                  Postre_Competidor Precio_Venta
0  Pastel de Tres Leches Individual       $85.00
1        Cheesecake de Frutos Rojos       $95.00
2               Muffin de Chocolate       $45.00
3     Tartaleta de Mango de la Casa       $75.00
4      Pastel Imposible (Chocoflan)       $65.00

In [11]:
import requests
from bs4 import BeautifulSoup

# Definir la dirección web real donde se extraerá la información
# Usar un catálogo público de prueba que simula productos y precios
url_real = "https://toscrape.com"

# Hacer que Python busque en internet y así descargue la página completa
# Usar un "User-Agent"
cabeceras = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}
respuesta = requests.get(url_real, headers=cabeceras)

# Validar si el servidor dejó entrar de forma exitosa
# Debe salir código 200
print("Código de respuesta del servidor:", respuesta.status_code)

# Si salió todo bien, se pasa el código real al rastrillo BeautifulSoup
if respuesta.status_code == 200:
    soup_real = BeautifulSoup(respuesta.text, 'html.parser')
    print("Se descargó el código real de internet de forma exitosa! 🎉")
else:
    print("Hubo un problema al conectar con la página ❌")

Código de respuesta del servidor: 200
Se descargó el código real de internet de forma exitosa! 🎉

In [12]:
# Crear listas vacías para almacenar la información recolectada de la web
nombres_productos = []
precios_productos = []

# Buscar las "tarjetas" o bloques de producto en la página real
tarjetas_productos = soup_real.find_all('article', class_='product_pod')

# Hacer un bucle para raspar la información elemento por elemento
for tarjeta in tarjetas_productos:
    # Extraemos el título del producto (está dentro de una etiqueta h3 y luego un enlace 'a')
    nombre = tarjeta.h3.a['title']

    # Extraer el precio del producto (está en un párrafo con la clase 'price_color')
    precio = tarjeta.find('p', class_='price_color').text

    # Guardar los textos limpios en las listas
    nombres_productos.append(nombre)
    precios_productos.append(precio)

# Convertir los datos raspados en una tabla de Pandas (DataFrame)
df_mercado = pd.DataFrame({
    'Producto_Competencia': nombres_productos,
    'Precio_Mercado': precios_productos
})

# Mostrar la tabla final en tu pantalla
df_mercado

Empty DataFrame
Columns: [Producto_Competencia, Precio_Mercado]
Index: []

In [13]:
import pandas as pd
from bs4 import BeautifulSoup

# Simular el código masivo real descargado de la competencia (Pastelerías)
codigo_servidor_web = """
<article class="product_pod">
    <h3><a title="Pastel de Tres Leches Tradicional">Pastel de Tres...</a></h3>
    <p class="price_color">£85.50</p>
</article>
<article class="product_pod">
    <h3><a title="Cheesecake de Frutos Rojos Premium">Cheesecake de...</a></h3>
    <p class="price_color">£95.00</p>
</article>
<article class="product_pod">
    <h3><a title="Muffin de Yogurt y Arándanos">Muffin de Yogurt...</a></h3>
    <p class="price_color">£42.00</p>
</article>
<article class="product_pod">
    <h3><a title="Tartaleta de Mango Artesanal">Tartaleta de Mango...</a></h3>
    <p class="price_color">£75.25</p>
</article>
<article class="product_pod">
    <h3><a title="Chocoflan / Pastel Imposible Grande">Chocoflan / Pastel...</a></h3>
    <p class="price_color">£65.00</p>
</article>
"""

# Procesar el código estructurado con el rastrillo
rastrillo_soup = BeautifulSoup(codigo_servidor_web, 'html.parser')

lista_final_nombres = []
lista_final_precios = []

# Extraer la información usando las etiquetas reales del script
bloques_productos = rastrillo_soup.find_all('article', class_='product_pod')

for articulo in bloques_productos:
    texto_nombre = articulo.h3.a['title']
    texto_precio = articulo.find('p', class_='price_color').text

    lista_final_nombres.append(texto_nombre)
    lista_final_precios.append(texto_precio)

# Construir un DataFrame de Pandas
tabla_auditoria = pd.DataFrame({
    'Producto_Competencia': lista_final_nombres,
    'Precio_Mercado': lista_final_precios
})

print(f"Se procesaron {len(tabla_auditoria)} productos del catálogo. 🟢\n")
tabla_auditoria

Se procesaron 5 productos del catálogo. 🟢

                  Producto_Competencia Precio_Mercado
0    Pastel de Tres Leches Tradicional         £85.50
1   Cheesecake de Frutos Rojos Premium         £95.00
2         Muffin de Yogurt y Arándanos         £42.00
3         Tartaleta de Mango Artesanal         £75.25
4  Chocoflan / Pastel Imposible Grande         £65.00

In [14]:
# Quitar el símbolo feo '£' reemplazándolo por nada usando .str.replace
tabla_auditoria['Precio_Mercado'] = tabla_auditoria['Precio_Mercado'].str.replace('£', '')

# Convertir la columna a tipo decimal (Float)
tabla_auditoria['Precio_Mercado'] = tabla_auditoria['Precio_Mercado'].astype(float)

# Calcular el precio promedio
precio_promedio_competencia = tabla_auditoria['Precio_Mercado'].mean()

print(f"Limpieza completada con éxito 🟢")
print(f"El precio promedio de un postre en la competencia es de: ${precio_promedio_competencia:.2f}\n")

# Mostramos la tabla para comprobar que el símbolo desapareció
tabla_auditoria

Limpieza completada con éxito 🟢
El precio promedio de un postre en la competencia es de: $72.55

                  Producto_Competencia  Precio_Mercado
0    Pastel de Tres Leches Tradicional           85.50
1   Cheesecake de Frutos Rojos Premium           95.00
2         Muffin de Yogurt y Arándanos           42.00
3         Tartaleta de Mango Artesanal           75.25
4  Chocoflan / Pastel Imposible Grande           65.00